Search.appendIndex(
    [
                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster",
            "name": "DynamicTypeCaster",
            "summary": "DynamicTypeCaster",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "DynamicTypeCaster.",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#method___construct"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003A__call\u0028\u0029",
            "name": "__call",
            "summary": "Forwards\u0020calls\u0020to\u0020Model,\u0020handles\u0020get\u0020and\u0020set\u0020methods\u0020from\u0020HasAttributes.",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#method___call"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003AgetCastedAttribute\u0028\u0029",
            "name": "getCastedAttribute",
            "summary": "Cast\u0020attribute\u0020from\u0020string\u0020to\u0020\u0040DataType.",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#method_getCastedAttribute"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003AnewInstance\u0028\u0029",
            "name": "newInstance",
            "summary": "New\u0020DynamicTypeCaster\u0020instance.",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#method_newInstance"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003AsetCastedAttribute\u0028\u0029",
            "name": "setCastedAttribute",
            "summary": "Cast\u0020attribute\u0020from\u0020\u0040DataType\u0020to\u0020string.",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#method_setCastedAttribute"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003AsetDataType\u0028\u0029",
            "name": "setDataType",
            "summary": "Set\u0020the\u0020\u0040DataType.",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#method_setDataType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003AsetKey\u0028\u0029",
            "name": "setKey",
            "summary": "Set\u0020the\u0020key.",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#method_setKey"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003AsetModel\u0028\u0029",
            "name": "setModel",
            "summary": "Set\u0020the\u0020model.",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#method_setModel"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003AsetModelAttributes\u0028\u0029",
            "name": "setModelAttributes",
            "summary": "Set\u0020the\u0020model\u0020attributes.",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#method_setModelAttributes"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003AsetValue\u0028\u0029",
            "name": "setValue",
            "summary": "Set\u0020the\u0020value\u0020to\u0020be\u0020cast.",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#method_setValue"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003AupdateCasts\u0028\u0029",
            "name": "updateCasts",
            "summary": "Update\u0020the\u0020casts\u0020array.",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#method_updateCasts"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003AvalidateInstance\u0028\u0029",
            "name": "validateInstance",
            "summary": "Is\u0020this\u0020instance\u0020valid\u003F",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#method_validateInstance"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003A\u0024model",
            "name": "model",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#property_model"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003A\u0024key",
            "name": "key",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#property_key"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#property_value"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003A\u0024modelAttributes",
            "name": "modelAttributes",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#property_modelAttributes"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters\\DynamicTypeCaster\u003A\u003A\u0024dataType",
            "name": "dataType",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Casters-DynamicTypeCaster.html#property_dataType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Collections\\SettingsCollection",
            "name": "SettingsCollection",
            "summary": "SettingsCollection",
            "url": "classes/Envorra-LaravelSettings-Collections-SettingsCollection.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Collections\\SettingsCollection\u003A\u003Afrom\u0028\u0029",
            "name": "from",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Collections-SettingsCollection.html#method_from"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Collections\\SettingsCollection\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "New\u0020collection\u0020from\u0020array.",
            "url": "classes/Envorra-LaravelSettings-Collections-SettingsCollection.html#method_fromArray"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Collections\\SettingsCollection\u003A\u003AfromJson\u0028\u0029",
            "name": "fromJson",
            "summary": "New\u0020collection\u0020from\u0020JSON.",
            "url": "classes/Envorra-LaravelSettings-Collections-SettingsCollection.html#method_fromJson"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\CastsCollections",
            "name": "CastsCollections",
            "summary": "CastsCollections",
            "url": "classes/Envorra-LaravelSettings-Contracts-CastsCollections.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\CastsCollections\u003A\u003Afrom\u0028\u0029",
            "name": "from",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Contracts-CastsCollections.html#method_from"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\CastsCollections\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "New\u0020collection\u0020from\u0020array.",
            "url": "classes/Envorra-LaravelSettings-Contracts-CastsCollections.html#method_fromArray"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\CastsCollections\u003A\u003AfromJson\u0028\u0029",
            "name": "fromJson",
            "summary": "New\u0020collection\u0020from\u0020JSON.",
            "url": "classes/Envorra-LaravelSettings-Contracts-CastsCollections.html#method_fromJson"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\DynamicallyCastsTypes",
            "name": "DynamicallyCastsTypes",
            "summary": "DynamicallyCastsTypes",
            "url": "classes/Envorra-LaravelSettings-Contracts-DynamicallyCastsTypes.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\DynamicallyCastsTypes\u003A\u003AgetDataType\u0028\u0029",
            "name": "getDataType",
            "summary": "Get\u0020the\u0020DataType\u0020for\u0020this\u0020Model.",
            "url": "classes/Envorra-LaravelSettings-Contracts-DynamicallyCastsTypes.html#method_getDataType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\ModelOwnership",
            "name": "ModelOwnership",
            "summary": "ModelOwnership",
            "url": "classes/Envorra-LaravelSettings-Contracts-ModelOwnership.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\ModelOwnership\u003A\u003AbelongsToModel\u0028\u0029",
            "name": "belongsToModel",
            "summary": "Is\u0020a\u0020Model\u0020the\u0020owner\u0020of\u0020this\u0020Model\u003F",
            "url": "classes/Envorra-LaravelSettings-Contracts-ModelOwnership.html#method_belongsToModel"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\ModelOwnership\u003A\u003AhasOwner\u0028\u0029",
            "name": "hasOwner",
            "summary": "Does\u0020the\u0020model\u0020have\u0020an\u0020owner\u003F",
            "url": "classes/Envorra-LaravelSettings-Contracts-ModelOwnership.html#method_hasOwner"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\ModelOwnership\u003A\u003Aowner\u0028\u0029",
            "name": "owner",
            "summary": "Owner\u0020relation.",
            "url": "classes/Envorra-LaravelSettings-Contracts-ModelOwnership.html#method_owner"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\ModelOwnership\u003A\u003AsetOwner\u0028\u0029",
            "name": "setOwner",
            "summary": "Set\u0020the\u0020owner\u0020of\u0020the\u0020model\u0020if\u0020new.",
            "url": "classes/Envorra-LaravelSettings-Contracts-ModelOwnership.html#method_setOwner"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\ProvidesArrayOfValues",
            "name": "ProvidesArrayOfValues",
            "summary": "ProvidesArrayOfValues",
            "url": "classes/Envorra-LaravelSettings-Contracts-ProvidesArrayOfValues.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\ProvidesArrayOfValues\u003A\u003Avalues\u0028\u0029",
            "name": "values",
            "summary": "Returns\u0020values\u0020of\u0020all\u0020cases\u0020in\u0020enum.",
            "url": "classes/Envorra-LaravelSettings-Contracts-ProvidesArrayOfValues.html#method_values"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository",
            "name": "Repository",
            "summary": "Repository",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Repository\u0020Constructor.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method___construct"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003Aapp\u0028\u0029",
            "name": "app",
            "summary": "Get\u0020app\u0020scoped\u0020repository.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_app"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003Aglobal\u0028\u0029",
            "name": "global",
            "summary": "Get\u0020global\u0020scoped\u0020repository.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_global"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003Ainstance\u0028\u0029",
            "name": "instance",
            "summary": "New\u0020repository\u0020instance.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_instance"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003Amodel\u0028\u0029",
            "name": "model",
            "summary": "Get\u0020model\u0020scoped\u0020repository.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_model"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003Auser\u0028\u0029",
            "name": "user",
            "summary": "Get\u0020user\u0020scoped\u0020repository.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_user"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "Get\u0020all\u0020the\u0020Settings.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_all"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003AallOfDataType\u0028\u0029",
            "name": "allOfDataType",
            "summary": "Get\u0020all\u0020Settings\u0020of\u0020a\u0020SettingType.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_allOfDataType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003AallOfSettingType\u0028\u0029",
            "name": "allOfSettingType",
            "summary": "Get\u0020all\u0020Settings\u0020of\u0020a\u0020SettingType.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_allOfSettingType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003AallRelatedToModel\u0028\u0029",
            "name": "allRelatedToModel",
            "summary": "Get\u0020all\u0020Settings\u0020related\u0020to\u0020a\u0020Model.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_allRelatedToModel"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Find\u0020a\u0020Setting.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_find"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003AfindOrFail\u0028\u0029",
            "name": "findOrFail",
            "summary": "Find\u0020a\u0020Setting,\u0020or\u0020fail.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_findOrFail"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020a\u0020Setting\u0027s\u0020value\u0020or\u0020the\u0020default.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_get"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003AnewQuery\u0028\u0029",
            "name": "newQuery",
            "summary": "New\u0020query.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_newQuery"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "Get\u0020the\u0020current\u0020query.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_query"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Set\u0020a\u0020setting.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_set"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003Awhere\u0028\u0029",
            "name": "where",
            "summary": "Where\u0020query.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_where"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\Repository\u003A\u003AwhereOwner\u0028\u0029",
            "name": "whereOwner",
            "summary": "Where\u0020the\u0020owner\u0020is.",
            "url": "classes/Envorra-LaravelSettings-Contracts-Repository.html#method_whereOwner"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\SettingOwner",
            "name": "SettingOwner",
            "summary": "SettingOwner",
            "url": "classes/Envorra-LaravelSettings-Contracts-SettingOwner.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts\\SettingOwner\u003A\u003Asettings\u0028\u0029",
            "name": "settings",
            "summary": "This\u0020Model\u0027s\u0020settings.",
            "url": "classes/Envorra-LaravelSettings-Contracts-SettingOwner.html#method_settings"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType",
            "name": "DataType",
            "summary": "DataType",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AaliasMap\u0028\u0029",
            "name": "aliasMap",
            "summary": "Map\u0020of\u0020data\u0020types\u0020and\u0020their\u0020aliases.",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_aliasMap"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AareAllOfPrimitiveType\u0028\u0029",
            "name": "areAllOfPrimitiveType",
            "summary": "Are\u0020all\u0020given\u0020data\u0020types\u0020the\u0020same\u0020primitive\u0020type\u003F",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_areAllOfPrimitiveType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AareAllOfType\u0028\u0029",
            "name": "areAllOfType",
            "summary": "Are\u0020all\u0020given\u0020data\u0020types\u0020the\u0020same\u0020type\u003F",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_areAllOfType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AclassMap\u0028\u0029",
            "name": "classMap",
            "summary": "Map\u0020of\u0020classes\u0020to\u0020their\u0020data\u0020types.",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_classMap"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AfromValue\u0028\u0029",
            "name": "fromValue",
            "summary": "New\u0020instance\u0020from\u0020the\u0020type\u0020of\u0020variable\u0020passed.",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_fromValue"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AintegerIsValidTimestamp\u0028\u0029",
            "name": "integerIsValidTimestamp",
            "summary": "Is\u0020a\u0020given\u0020integer\u0020a\u0020valid\u0020timestamp\u003F",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_integerIsValidTimestamp"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AprimitiveMap\u0028\u0029",
            "name": "primitiveMap",
            "summary": "Map\u0020of\u0020data\u0020types\u0020to\u0020their\u0020primitive\u0020counterparts.",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_primitiveMap"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003Aprimitives\u0028\u0029",
            "name": "primitives",
            "summary": "PHP\u0020primitive\u0020data\u0020types.",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_primitives"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AstringIsValidJson\u0028\u0029",
            "name": "stringIsValidJson",
            "summary": "Is\u0020a\u0020given\u0020string\u0020valid\u0020JSON\u003F",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_stringIsValidJson"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003Avalues\u0028\u0029",
            "name": "values",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_values"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003Aaliases\u0028\u0029",
            "name": "aliases",
            "summary": "The\u0020data\u0020type\u0027s\u0020aliases.",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_aliases"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AconvertValueToString\u0028\u0029",
            "name": "convertValueToString",
            "summary": "Convert\u0020the\u0020inbound\u0020value\u0020to\u0020its\u0020string\u0020representation.",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_convertValueToString"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003Ais\u0028\u0029",
            "name": "is",
            "summary": "Checks\u0020if\u0020the\u0020given\u0020type\u0020is\u0020the\u0020same\u0020as\u0020this\u0020one.",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_is"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AisIn\u0028\u0029",
            "name": "isIn",
            "summary": "Check\u0020if\u0020this\u0020data\u0020type\u0020is\u0020any\u0020of\u0020the\u0020given\u0020ones.",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_isIn"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AisPrimitive\u0028\u0029",
            "name": "isPrimitive",
            "summary": "Is\u0020this\u0020type\u0020a\u0020primitive\u0020type\u003F",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_isPrimitive"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AresolveObjectClass\u0028\u0029",
            "name": "resolveObjectClass",
            "summary": "Resolve\u0020the\u0020class\u0020from\u0020the\u0020data\u0020type.",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_resolveObjectClass"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AtoPrimitive\u0028\u0029",
            "name": "toPrimitive",
            "summary": "Convert\u0020this\u0020data\u0020type\u0020to\u0020its\u0020primitive\u0020version.",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_toPrimitive"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AvalueIsType\u0028\u0029",
            "name": "valueIsType",
            "summary": "Is\u0020the\u0020given\u0020value\u0020the\u0020same\u0020type\u0020as\u0020this\u0020instance\u003F",
            "url": "classes/Envorra-LaravelSettings-Enums-DataType.html#method_valueIsType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AARRAY",
            "name": "ARRAY",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003ABOOL",
            "name": "BOOL",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003ABOOLEAN",
            "name": "BOOLEAN",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003ACOLLECTION",
            "name": "COLLECTION",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003ADATE",
            "name": "DATE",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003ADATETIME",
            "name": "DATETIME",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003ADOUBLE",
            "name": "DOUBLE",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AFLOAT",
            "name": "FLOAT",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AINT",
            "name": "INT",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AINTEGER",
            "name": "INTEGER",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AJSON",
            "name": "JSON",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AOBJECT",
            "name": "OBJECT",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003AREAL",
            "name": "REAL",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003ASTRING",
            "name": "STRING",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\DataType\u003A\u003ATIMESTAMP",
            "name": "TIMESTAMP",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\SettingType",
            "name": "SettingType",
            "summary": "SettingType",
            "url": "classes/Envorra-LaravelSettings-Enums-SettingType.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\SettingType\u003A\u003Amake\u0028\u0029",
            "name": "make",
            "summary": "Make\u0020a\u0020new\u0020instance\u0020from\u0020given.",
            "url": "classes/Envorra-LaravelSettings-Enums-SettingType.html#method_make"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\SettingType\u003A\u003Avalues\u0028\u0029",
            "name": "values",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Enums-SettingType.html#method_values"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\SettingType\u003A\u003Ais\u0028\u0029",
            "name": "is",
            "summary": "Check\u0020if\u0020this\u0020type\u0020is\u0020same\u0020as\u0020given\u0020type.",
            "url": "classes/Envorra-LaravelSettings-Enums-SettingType.html#method_is"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\SettingType\u003A\u003AisIn\u0028\u0029",
            "name": "isIn",
            "summary": "Check\u0020if\u0020this\u0020type\u0020is\u0020in\u0020given\u0020types.",
            "url": "classes/Envorra-LaravelSettings-Enums-SettingType.html#method_isIn"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\SettingType\u003A\u003AGLOBAL",
            "name": "GLOBAL",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\SettingType\u003A\u003AAPP",
            "name": "APP",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\SettingType\u003A\u003AMODEL",
            "name": "MODEL",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums\\SettingType\u003A\u003AUSER",
            "name": "USER",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Exceptions\\CastCollectionException",
            "name": "CastCollectionException",
            "summary": "CastCollectionException",
            "url": "classes/Envorra-LaravelSettings-Exceptions-CastCollectionException.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Exceptions\\DataTypeException",
            "name": "DataTypeException",
            "summary": "DataTypeException",
            "url": "classes/Envorra-LaravelSettings-Exceptions-DataTypeException.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Facades\\Setting",
            "name": "Setting",
            "summary": "Setting",
            "url": "classes/Envorra-LaravelSettings-Facades-Setting.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Facades\\Setting\u003A\u003AgetFacadeAccessor\u0028\u0029",
            "name": "getFacadeAccessor",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Facades-Setting.html#method_getFacadeAccessor"
        },                {
            "fqsen": "\\setting\u0028\u0029",
            "name": "setting",
            "summary": "",
            "url": "namespaces/default.html#function_setting"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\LaravelSettingsProvider",
            "name": "LaravelSettingsProvider",
            "summary": "LaravelSettingsProvider",
            "url": "classes/Envorra-LaravelSettings-LaravelSettingsProvider.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\LaravelSettingsProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-LaravelSettingsProvider.html#method_boot"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\LaravelSettingsProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-LaravelSettingsProvider.html#method_register"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models\\Setting",
            "name": "Setting",
            "summary": "Setting",
            "url": "classes/Envorra-LaravelSettings-Models-Setting.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models\\Setting\u003A\u003AmodelFromArray\u0028\u0029",
            "name": "modelFromArray",
            "summary": "Get\u0020a\u0020new\u0020model\u0020instance\u0020from\u0020an\u0020array.",
            "url": "classes/Envorra-LaravelSettings-Models-Setting.html#method_modelFromArray"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models\\Setting\u003A\u003AmodelFromJson\u0028\u0029",
            "name": "modelFromJson",
            "summary": "Get\u0020a\u0020new\u0020model\u0020instance\u0020from\u0020JSON.",
            "url": "classes/Envorra-LaravelSettings-Models-Setting.html#method_modelFromJson"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models\\Setting\u003A\u003AgetDataType\u0028\u0029",
            "name": "getDataType",
            "summary": "Get\u0020the\u0020DataType\u0020for\u0020this\u0020Model.",
            "url": "classes/Envorra-LaravelSettings-Models-Setting.html#method_getDataType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models\\Setting\u003A\u003AisAppSetting\u0028\u0029",
            "name": "isAppSetting",
            "summary": "Is\u0020this\u0020an\u0020App\u0020setting\u003F",
            "url": "classes/Envorra-LaravelSettings-Models-Setting.html#method_isAppSetting"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models\\Setting\u003A\u003AisGlobalSetting\u0028\u0029",
            "name": "isGlobalSetting",
            "summary": "Is\u0020this\u0020a\u0020Global\u0020setting\u003F",
            "url": "classes/Envorra-LaravelSettings-Models-Setting.html#method_isGlobalSetting"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models\\Setting\u003A\u003AisModelSetting\u0028\u0029",
            "name": "isModelSetting",
            "summary": "Is\u0020this\u0020a\u0020Model\u0020setting\u003F",
            "url": "classes/Envorra-LaravelSettings-Models-Setting.html#method_isModelSetting"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models\\Setting\u003A\u003AisSettingType\u0028\u0029",
            "name": "isSettingType",
            "summary": "Check\u0020if\u0020this\u0020is\u0020the\u0020same\u0020SettingType\u0020as\u0020given.",
            "url": "classes/Envorra-LaravelSettings-Models-Setting.html#method_isSettingType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models\\Setting\u003A\u003AisUserSetting\u0028\u0029",
            "name": "isUserSetting",
            "summary": "Is\u0020this\u0020a\u0020User\u0020setting\u003F",
            "url": "classes/Envorra-LaravelSettings-Models-Setting.html#method_isUserSetting"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models\\Setting\u003A\u003AnewCollection\u0028\u0029",
            "name": "newCollection",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Models-Setting.html#method_newCollection"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models\\Setting\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Models-Setting.html#property_casts"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models\\Setting\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Models-Setting.html#property_fillable"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository",
            "name": "SettingsRepository",
            "summary": "SettingsRepository",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Repository\u0020Constructor.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method___construct"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003Aapp\u0028\u0029",
            "name": "app",
            "summary": "Get\u0020app\u0020scoped\u0020repository.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_app"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003Aglobal\u0028\u0029",
            "name": "global",
            "summary": "Get\u0020global\u0020scoped\u0020repository.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_global"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003Ainstance\u0028\u0029",
            "name": "instance",
            "summary": "New\u0020repository\u0020instance.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_instance"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003Amodel\u0028\u0029",
            "name": "model",
            "summary": "Get\u0020model\u0020scoped\u0020repository.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_model"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003Auser\u0028\u0029",
            "name": "user",
            "summary": "Get\u0020user\u0020scoped\u0020repository.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_user"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "Get\u0020all\u0020the\u0020Settings.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_all"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003AallOfDataType\u0028\u0029",
            "name": "allOfDataType",
            "summary": "Get\u0020all\u0020Settings\u0020of\u0020a\u0020SettingType.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_allOfDataType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003AallOfSettingType\u0028\u0029",
            "name": "allOfSettingType",
            "summary": "Get\u0020all\u0020Settings\u0020of\u0020a\u0020SettingType.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_allOfSettingType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003AallRelatedToModel\u0028\u0029",
            "name": "allRelatedToModel",
            "summary": "Get\u0020all\u0020Settings\u0020related\u0020to\u0020a\u0020Model.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_allRelatedToModel"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Find\u0020a\u0020Setting.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_find"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003AfindOrFail\u0028\u0029",
            "name": "findOrFail",
            "summary": "Find\u0020a\u0020Setting,\u0020or\u0020fail.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_findOrFail"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020a\u0020Setting\u0027s\u0020value\u0020or\u0020the\u0020default.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_get"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003AgetModel\u0028\u0029",
            "name": "getModel",
            "summary": "Get\u0020the\u0020model.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_getModel"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003AnewQuery\u0028\u0029",
            "name": "newQuery",
            "summary": "New\u0020query.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_newQuery"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#property_query"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Set\u0020a\u0020setting.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_set"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003Awhere\u0028\u0029",
            "name": "where",
            "summary": "Where\u0020query.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_where"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003AwhereOwner\u0028\u0029",
            "name": "whereOwner",
            "summary": "Where\u0020the\u0020owner\u0020is.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_whereOwner"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003AfilterQuery\u0028\u0029",
            "name": "filterQuery",
            "summary": "Add\u0020where\u0020clauses\u0020to\u0020filter\u0020the\u0020query.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_filterQuery"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003AnormalizeCollection\u0028\u0029",
            "name": "normalizeCollection",
            "summary": "Normalize\u0020the\u0020Collection\u0020to\u0020a\u0020SettingsCollection.",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#method_normalizeCollection"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003A\u0024scopeSettingType",
            "name": "scopeSettingType",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#property_scopeSettingType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003A\u0024scopeOwner",
            "name": "scopeOwner",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#property_scopeOwner"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories\\SettingsRepository\u003A\u003A\u0024scopeDataType",
            "name": "scopeDataType",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Repositories-SettingsRepository.html#property_scopeDataType"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\AliasesSnakeCaseAttributes",
            "name": "AliasesSnakeCaseAttributes",
            "summary": "AliasesSnakeCaseAttributes",
            "url": "classes/Envorra-LaravelSettings-Traits-AliasesSnakeCaseAttributes.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\AliasesSnakeCaseAttributes\u003A\u003AgetAttribute\u0028\u0029",
            "name": "getAttribute",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Traits-AliasesSnakeCaseAttributes.html#method_getAttribute"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\AliasesSnakeCaseAttributes\u003A\u003AgetConnection\u0028\u0029",
            "name": "getConnection",
            "summary": "Get\u0020the\u0020database\u0020connection\u0020for\u0020the\u0020model.",
            "url": "classes/Envorra-LaravelSettings-Traits-AliasesSnakeCaseAttributes.html#method_getConnection"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\AliasesSnakeCaseAttributes\u003A\u003AgetTable\u0028\u0029",
            "name": "getTable",
            "summary": "Get\u0020the\u0020table\u0020associated\u0020with\u0020the\u0020model.",
            "url": "classes/Envorra-LaravelSettings-Traits-AliasesSnakeCaseAttributes.html#method_getTable"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\AliasesSnakeCaseAttributes\u003A\u003AsetAttribute\u0028\u0029",
            "name": "setAttribute",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Traits-AliasesSnakeCaseAttributes.html#method_setAttribute"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\HasOwner",
            "name": "HasOwner",
            "summary": "HasOwner",
            "url": "classes/Envorra-LaravelSettings-Traits-HasOwner.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\HasOwner\u003A\u003AbelongsToModel\u0028\u0029",
            "name": "belongsToModel",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Traits-HasOwner.html#method_belongsToModel"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\HasOwner\u003A\u003AhasOwner\u0028\u0029",
            "name": "hasOwner",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Traits-HasOwner.html#method_hasOwner"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\HasOwner\u003A\u003AmorphTo\u0028\u0029",
            "name": "morphTo",
            "summary": "Define\u0020a\u0020polymorphic,\u0020inverse\u0020one\u002Dto\u002Done\u0020or\u0020many\u0020relationship.",
            "url": "classes/Envorra-LaravelSettings-Traits-HasOwner.html#method_morphTo"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\HasOwner\u003A\u003Aowner\u0028\u0029",
            "name": "owner",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Traits-HasOwner.html#method_owner"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\HasOwner\u003A\u003AsetOwner\u0028\u0029",
            "name": "setOwner",
            "summary": "",
            "url": "classes/Envorra-LaravelSettings-Traits-HasOwner.html#method_setOwner"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\HasSettings",
            "name": "HasSettings",
            "summary": "HasSettings",
            "url": "classes/Envorra-LaravelSettings-Traits-HasSettings.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\HasSettings\u003A\u003AmorphMany\u0028\u0029",
            "name": "morphMany",
            "summary": "Define\u0020a\u0020polymorphic\u0020one\u002Dto\u002Dmany\u0020relationship.",
            "url": "classes/Envorra-LaravelSettings-Traits-HasSettings.html#method_morphMany"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits\\HasSettings\u003A\u003Asettings\u0028\u0029",
            "name": "settings",
            "summary": "Model\u0020has\u0020settings.",
            "url": "classes/Envorra-LaravelSettings-Traits-HasSettings.html#method_settings"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Casters",
            "name": "Casters",
            "summary": "",
            "url": "namespaces/envorra-laravelsettings-casters.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Collections",
            "name": "Collections",
            "summary": "",
            "url": "namespaces/envorra-laravelsettings-collections.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Contracts",
            "name": "Contracts",
            "summary": "",
            "url": "namespaces/envorra-laravelsettings-contracts.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Enums",
            "name": "Enums",
            "summary": "",
            "url": "namespaces/envorra-laravelsettings-enums.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/envorra-laravelsettings-exceptions.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Facades",
            "name": "Facades",
            "summary": "",
            "url": "namespaces/envorra-laravelsettings-facades.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings",
            "name": "LaravelSettings",
            "summary": "",
            "url": "namespaces/envorra-laravelsettings.html"
        },                {
            "fqsen": "\\Envorra",
            "name": "Envorra",
            "summary": "",
            "url": "namespaces/envorra.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/envorra-laravelsettings-models.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Repositories",
            "name": "Repositories",
            "summary": "",
            "url": "namespaces/envorra-laravelsettings-repositories.html"
        },                {
            "fqsen": "\\Envorra\\LaravelSettings\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/envorra-laravelsettings-traits.html"
        }            ]
);
